CC     = mpicc
CFLAGS = -g -Wall -O3
LDLIBS = -lm


OBJS =  cfg.o\
    lib.o \
    timer.o \
    elib.o \
	pclust.o\
    dtype.o \
    producer.o\
    buffer.o \
    master.o\
    queue.o\
    forest.o \
    pairs.o \
    sort.o \
    dynamic.o \
    loadseq.o \
    spmaster.o \
    cslib.o \
    rpool.o \
    spool.o \
    cpool.o \
    consumer.o \
    

all: pclust

pclust: $(OBJS)
	$(CC) $(OBJS) -o pclust $(LDLIBS)

install:
	cp ./pclust  ~/bin/pclust

clean:
	rm -f *.o pclust
